Test run with arch variables

diff --git a/root/etc/cont-init.d/30-install b/root/etc/cont-init.d/30-install
--- a/root/etc/cont-init.d/30-install
+++ b/root/etc/cont-init.d/30-install
@@ -1,9 +1,32 @@
 #!/usr/bin/with-contenv bash
 
+echo "Empty arch variable found, setting arch variable to x86-64 for standard operation"
+[ -z "$ARCH_VAR" ] && ARCH_VAR="x86-64"
+
+echo "Checking for valid arch options"
+case $ARCH_VAR in
+  x86-64)
+    echo "Proceeding with x86-64 arch"
+    ;;
+  aarch64)
+    echo "Proceeding with aarch64 arch"
+    ;;
+  arm5)
+    echo "Proceeding with arm5 arch"
+    ;;
+  arm)
+    echo "Proceeding with arm arch"
+    ;;
+  *)
+    echo "Unrecognized or invalid arch selection, canceling install"
+    exit 1
+    ;;
+esac
+
 # Grab latest versions of the app
-wget -O /bin/airupnp-x86-64 https://raw.githubusercontent.com/philippe44/AirConnect/master/bin/airupnp-x86-64 && chmod +x /bin/airupnp-x86-64
-wget -O /bin/aircast-x86-64 https://raw.githubusercontent.com/philippe44/AirConnect/master/bin/aircast-x86-64 && chmod +x /bin/aircast-x86-64
+wget -O /bin/airupnp-$ARCH_VAR https://raw.githubusercontent.com/philippe44/AirConnect/master/bin/airupnp-$ARCH_VAR && chmod +x /bin/airupnp-$ARCH_VAR
+wget -O /bin/aircast-$ARCH_VAR https://raw.githubusercontent.com/philippe44/AirConnect/master/bin/aircast-$ARCH_VAR && chmod +x /bin/aircast-$ARCH_VAR
 
 # Insert runtime commands if users has entered them as environment variables
-[ -z "$AIRUPNP_VAR" ] || sed -i 's;command=/bin/airupnp-x86-64 -l 1000:2000;command=/bin/airupnp-x86-64 '"$AIRUPNP_VAR"';' /etc/supervisord.conf
-[ -z "$AIRCAST_VAR" ] || sed -i 's;command=/bin/aircast-x86-64;command=/bin/aircast-x86-64 '"$AIRCAST_VAR"';' /etc/supervisord.conf
+[ -z "$AIRUPNP_VAR" ] || sed -i 's;command=/bin/airupnp-$ARCH_VAR -l 1000:2000;command=/bin/airupnp-'"$ARCH_VAR $AIRUPNP_VAR"';' /etc/supervisord.conf
+[ -z "$AIRCAST_VAR" ] || sed -i 's;command=/bin/aircast-$ARCH_VAR;command=/bin/aircast-'"$ARCH_VAR $AIRCAST_VAR"';' /etc/supervisord.conf
